host_panel/applications/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (
    WebApplicationListView,
    WebApplicationCreateView,
    WebApplicationDetailView,
    WebApplicationDeleteView,
    WebappSSHKeyListView,
    WebappSSHKeyCreateView,
    WebappSSHKeyDeleteView,
    DatabaseUserCreateView,
    DatabaseUserDeleteView,
    DatabaseCreateView,
    DatabaseDeleteView,
    LinkedFTPListView,
    LinkedFTPCreateView,
    LinkedFTPDeleteView,
    DomainListView,
    DomainCreateView,
    DomainDeleteView,
    BackupToFTPLinkCreateView,
    BackupToFTPLinkDeleteView,
)


urlpatterns = patterns(
    'applications.views',
    url(
        r'^(?P<app_pk>\d+)/linkedftps/add/$',
        LinkedFTPCreateView.as_view(), name='webapp_add_linkedftp'),
    url(
        r'^(?P<app_pk>\d+)/linkedftps/(?P<pk>\d+)/remove/$',
        LinkedFTPDeleteView.as_view(), name='webapp_remove_linkedftp'),
    url(
        r'^(?P<app_pk>\d+)/linkedftps/$',
        LinkedFTPListView.as_view(), name='webapp_linkedftps'),


    url(
        r'^(?P<app_pk>\d+)/sshkeys/$',
        WebappSSHKeyListView.as_view(), name='webapp_sshkeys'),
    url(
        r'^(?P<app_pk>\d+)/sshkeys/add/$',
        WebappSSHKeyCreateView.as_view(),
        name='webapp_add_sshkey'),
    url(
        r'^(?P<app_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        WebappSSHKeyDeleteView.as_view(),
        name='webapp_remove_sshkey'),

    url(
        r'^(?P<app_pk>\d+)/domains/$',
        DomainListView.as_view(), name='webapp_domains'),
    url(
        r'^(?P<app_pk>\d+)/domains/(?P<pk>\d+)/remove/$',
        DomainDeleteView.as_view(), name='webapp_remove_domain'),
    url(
        r'^(?P<app_pk>\d+)/domains/(?P<pk>\d+)/set-default/$',
        'set_default_domain', name='webapp_set_default_domain'),
    url(
        r'^(?P<app_pk>\d+)/domains/add/$',
        DomainCreateView.as_view(), name='webapp_add_domain'),

    url(r'^(?P<app_pk>\d+)/files/$', 'files', name='webapp_files'),

    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/add/$',
        DatabaseCreateView.as_view(), name='webapp_add_pgdb'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/(?P<pk>\d+)/remove/$',
        DatabaseDeleteView.as_view(), name='webapp_remove_pgdb'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/(?P<pk>\d+)/connection/$',
        'pg_connection', name='webapp_pgconnection'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/(?P<pk>\d+)/dumps/$',
        'pg_dumps', name='webapp_pgdumps'),

    url(
        r'^(?P<app_pk>\d+)/databases/pgusers/(?P<pk>\d+)/remove/$',
        DatabaseUserDeleteView.as_view(), name='webapp_remove_pguser'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgusers/add/$',
        DatabaseUserCreateView.as_view(), name='webapp_add_pguser'),
    url(
        r'^(?P<app_pk>\d+)/databases/$',
        'databases', name='webapp_databases'),

    url(
        r'^(?P<pk>\d+)/remove/$',
        WebApplicationDeleteView.as_view(), name='remove_webapp'),
    url(
        r'^(?P<pk>\d+)/$',
        WebApplicationDetailView.as_view(), name='webapp'),
    url(
        r'^add/$',
        WebApplicationCreateView.as_view(), name='add_webapp'),
    url(
        r'^$',
        WebApplicationListView.as_view(), name='application_list'),

    url(
        r'^(?P<app_pk>\d+)/backups/$',
        'backups_view', name='webapp_backups'),
    url(
        r'^(?P<app_pk>\d+)/backups/ftp-links/add/$',
        BackupToFTPLinkCreateView.as_view(), name='webapp_add_backup_ftp'),
    url(
        r'^(?P<app_pk>\d+)/backups/ftp-links/(?P<pk>\d+)/remove/$',
        BackupToFTPLinkDeleteView.as_view(), name='webapp_remove_backup_ftp'),
    url(
        r'^(?P<app_pk>\d+)/backups/edit/$',
        'configure_backups', name='webapp_configure_backups'),

    url(
        r'^(?P<app_pk>\d+)/settings/change-mode/$',
        'change_settings_mode', name='webapp_settings_mode'),
    url(
        r'^(?P<app_pk>\d+)/settings/restart-nginx/$',
        'restart_nginx', name='webapp_restart_nginx'),
    url(
        r'^(?P<app_pk>\d+)/settings/$',
        'settings', name='webapp_settings'),
)

host_panel/host_panel/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns(
    '',
    url(r'^$', 'host_panel.views.home', name='home'),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^hosts/', include('hosts.urls', namespace='hosts')),
    url(r'^applications/', include('applications.urls', namespace='applications')),
    url(r'^sshkeys/', include('sshkeys.urls', namespace='sshkeys')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

host_panel/hosts/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (
    HostListView,
    HostDetailView,
    HostCreateView,
    HostSSHKeyListView,
    HostSSHKeyCreateView,
    HostSSHKeyDeleteView,
    FTPUserListView,
    FTPUserCreateView,
    FTPUserDeleteView,
    DatabaseServiceListView,
    DatabaseServiceCreateView,
    DatabaseServiceDetailView,
    DatabaseServiceDeleteView,
    DatabaseServiceSSHKeyCreateView,
    DatabaseServiceSSHKeyDeleteView,
    HipacheInfoView,
    HipacheSSHKeyCreateView,
    HipacheSSHKeyDeleteView,
    CronTaskListView,
    CronTaskCreateView,
    CronTaskUpdateView,
    CronTaskDeleteView,
)

urlpatterns = patterns(
    'hosts.views',
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/(?P<pk>\d+)/remove/$',
        HipacheSSHKeyDeleteView.as_view(), name='host_routing_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/add/$',
        HipacheSSHKeyCreateView.as_view(), name='host_routing_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/install/$',
        'install_hipache', name='host_install_routing'),
    url(
        r'^(?P<host_pk>\d+)/routing/update-hipache-db/$',
        'update_hipache_db', name='host_update_hipache_db'),
    url(
        r'^(?P<host_pk>\d+)/routing/$',
        HipacheInfoView.as_view(), name='host_routing'),

    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<db_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        DatabaseServiceSSHKeyDeleteView.as_view(),
        name='host_database_service_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/sshkeys/add/$',
        DatabaseServiceSSHKeyCreateView.as_view(),
        name='host_database_service_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/remove/$',
        DatabaseServiceDeleteView.as_view(),
        name='host_remove_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/$',
        DatabaseServiceDetailView.as_view(), name='host_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/add/$',
        DatabaseServiceCreateView.as_view(), name='host_add_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/$',
        DatabaseServiceListView.as_view(), name='host_database_services'),

    url(
        r'^(?P<host_pk>\d+)/ftpusers/add/$',
        FTPUserCreateView.as_view(), name='host_add_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/(?P<pk>\d+)/remove/$',
        FTPUserDeleteView.as_view(), name='host_remove_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/$',
        FTPUserListView.as_view(), name='host_ftpusers'),

    url(
        r'^(?P<host_pk>\d+)/run-command/(?P<button_id>\d+)/$',
        'host_run_command', name='run_command'),

    url(
        r'^(?P<host_pk>\d+)/sshkeys/add/$',
        HostSSHKeyCreateView.as_view(), name='host_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        HostSSHKeyDeleteView.as_view(), name='host_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/$',
        HostSSHKeyListView.as_view(), name='host_sshkeys'),

    url(
        r'^(?P<host_pk>\d+)/crontasks/add/$',
        CronTaskCreateView.as_view(), name='host_add_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/edit/$',
        CronTaskUpdateView.as_view(), name='host_edit_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/remove/$',
        CronTaskDeleteView.as_view(), name='host_remove_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/$',
        CronTaskListView.as_view(), name='host_crontasks'),

    url(
        r'^(?P<pk>\d+)/host-setup.sh$',
        'setup_script', name='host_setup_script'),
    url(
        r'^(?P<pk>\d+)/mark-manageable/$',
        'mark_manageable', name='host_mark_manageable'),

    url(
        r'^(?P<pk>\d+)/detail/$',
        HostDetailView.as_view(), name='host_detail'),
    url(r'^add/$', HostCreateView.as_view(), name='add_host'),
    url(r'^$', HostListView.as_view(), name='host_list'),
)

host_panel/applications/forms.py
# coding: utf-8
from django import forms
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django.conf import settings
from crispy_forms.layout import (
    Layout,
    Field,
    MultiField,
)
from crispy_forms.bootstrap import AppendedText
from .models import (
    WebApplication,
    Domain,
    LinkedFTP,
    PostgreSQLUser,
    PostgreSQLDatabase,
    BackupSettings,
    ServerSettings,
    BackupToFTPLink,
)
from containers.models import DockerImage
# from django_select2.widgets import Select2MultipleWidget
from codemirror import CodeMirrorTextarea


class EasyConfigForm(forms.ModelForm):
    class Meta:
        model = ServerSettings
        fields = [
            'public_root', 'passenger_app_root', 'extra_top',
            'passenger_enabled', 'passenger_user',
            'passenger_friendly_error_pages', 'passenger_python',
            'passenger_max_pool_size',
            'passenger_min_instances',
            'passenger_pool_idle_time',
            'passenger_max_preloader_idle_time',
            'passenger_start_timeout',
            'passenger_max_requests',
            'passenger_pre_start',
            'passenger_max_request_queue_size',
            'passenger_request_queue_overflow_status_code',
            'passenger_ignore_client_abort',
            'passenger_intercept_errors',
            'passenger_pass_header',
            'passenger_buffer_response',
            'passenger_log_level', 'passenger_debug_log_file',
            'set_real_ip_from', 'real_ip_header', 'extra_tail',
            'auth_enabled',
            'auth_user',
            'auth_password',
            'auth_exlude_ips',
        ]
        widgets = {
            'extra_top': CodeMirrorTextarea(
                mode="nginx", config={'fixedGutter': True}),
            'extra_tail': CodeMirrorTextarea(
                mode="nginx", config={'fixedGutter': True}),
            # 'auth_password': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(EasyConfigForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
            Fieldset(
                _(u'Project root'),
                'public_root',
                'passenger_app_root',
            ),
            Fieldset(
                _(u'Extra top'),
                'extra_top',
            ),
            Fieldset(
                _(u'Basic Passenger settings'),
                'passenger_enabled',
                'passenger_user',
                'passenger_friendly_error_pages',
                'passenger_python',
            ),
            Fieldset(
                _(u'Advanced Passenger settings'),
                'passenger_max_pool_size',
                'passenger_min_instances',
                'passenger_pool_idle_time',
                'passenger_max_preloader_idle_time',
                'passenger_start_timeout',
                'passenger_max_requests',
                'passenger_pre_start',
                'passenger_max_request_queue_size',
                'passenger_request_queue_overflow_status_code',
                'passenger_ignore_client_abort',
                'passenger_intercept_errors',
                'passenger_pass_header',
                'passenger_buffer_response',
            ),
            Fieldset(
                _(u'Debug log'),
                'passenger_log_level',
                'passenger_debug_log_file',
            ),
            Fieldset(
                _(u'IP fix'),
                'set_real_ip_from',
                'real_ip_header',
            ),
            Fieldset(
                _(u'Extra tail'),
                'extra_tail',
            ),
            Fieldset(
                _(u'Authentication'),
                'auth_enabled',
                'auth_user',
                'auth_password',
                'auth_exlude_ips',
            ),
            ButtonHolder(
                Submit('submit', _(u'Save'), css_class='btn btn-primary')
            )
        )


class EditServerConfigFileForm(forms.Form):
    config = forms.CharField(
        label=_(u'webapp.conf'),
        widget=CodeMirrorTextarea(
            mode="nginx", config={'fixedGutter': True}))


class EditBackupSettingsForm(forms.ModelForm):
    class Meta:
        model = BackupSettings
        fields = [
            'cron_time_for_db', 'keep_db_files',
            'cron_time_for_fs', 'keep_fs_files',
        ]


class AddWebApplicationForm(forms.ModelForm):
    docker_image = forms.ModelChoiceField(
        queryset=DockerImage.objects.filter(is_webapp=True),
        label=_(u'Docker image'))

    class Meta:
        model = WebApplication
        fields = ['short_description', 'name', 'host']

    def __init__(self, customer, *args, **kwargs):
        from hosts.models import Host
        super(AddWebApplicationForm, self).__init__(*args, **kwargs)
        self.customer = customer
        self.fields['host'].queryset = Host.objects.all()

        try:
            max_app_id = \
                WebApplication.objects.order_by('-id').first().id + 1
        except AttributeError:
            max_app_id = 1
        self.fields['name'].initial = 'webapp_{0:02d}'.format(max_app_id)


class AddDomainForm(forms.ModelForm):
    class Meta:
        model = Domain
        fields = ['domain', 'protocol']
        # widgets = {
        #     'applications': Select2MultipleWidget(),
        # }

    def __init__(self, webapp, *args, **kwargs):
        super(AddDomainForm, self).__init__(*args, **kwargs)


class AddLinkedFTPForm(forms.ModelForm):
    class Meta:
        model = LinkedFTP
        fields = ['ftpuser', 'directory', 'ftp_directory']

    def __init__(self, webapp, *args, **kwargs):
        from hosts.models import FTPUser
        super(AddLinkedFTPForm, self).__init__(*args, **kwargs)
        self.webapp = webapp
        self.fields['ftpuser'].queryset = \
            FTPUser.objects.filter(
                owner=webapp.owner)


class BackupToFTPLinkForm(forms.ModelForm):
    class Meta:
        model = BackupToFTPLink
        fields = ['ftpuser', 'ftp_directory']

    def __init__(self, webapp, *args, **kwargs):
        from hosts.models import FTPUser
        super(BackupToFTPLinkForm, self).__init__(*args, **kwargs)
        self.webapp = webapp
        self.fields['ftpuser'].queryset = \
            FTPUser.objects.filter(
                owner=webapp.owner)


class AddPostgreSQLUserForm(forms.ModelForm):
    class Meta:
        model = PostgreSQLUser
        fields = [
            'pg_service',
            'username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, customer, host, *args, **kwargs):
        super(AddPostgreSQLUserForm, self).__init__(*args, **kwargs)
        self.host = host
        self.customer = customer
        self.pg_services = self.host.postgresql_servers.all()
        self.fields['pg_service'].queryset = self.pg_services
        self.fields['pg_service'].initial = \
            self.pg_services.get(is_default=True)

    def clean_username(self):
        already_exist = PostgreSQLUser.objects.filter(
            pg_service=self.pg_services,
            username=self.cleaned_data['username']).exists()

        if not already_exist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_(u'User already exists.'))


class AddPostgreSQLDatabaseForm(forms.ModelForm):
    pg_user = forms.ModelChoiceField(
        label=_(u'User name'), queryset=PostgreSQLUser.objects.none())

    class Meta:
        model = PostgreSQLDatabase
        fields = ['name']

    def __init__(self, customer, host, *args, **kwargs):
        super(AddPostgreSQLDatabaseForm, self).__init__(*args, **kwargs)
        self.host = host
        self.customer = customer
        self.pg_services = self.host.postgresql_servers.all()
        self.fields['pg_user'].queryset = PostgreSQLUser.objects.filter(
            pg_service=self.pg_services,
            owner=customer,
        )

    def clean_name(self):
        already_exist = PostgreSQLDatabase.objects.filter(
            pg_service=self.pg_services,
            name=self.cleaned_data['name']).exists()

        if not already_exist:
            return self.cleaned_data['name']
        raise forms.ValidationError(_(u'Database already exists.'))

host_panel/applications/templates/applications/databases.html
{% extends "applications/webapp_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load navigation_tags %}

{% block breadcrumbs %}
{{ block.super }}
<li class="active">{% trans "Databases" %}</li>
{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
    <a class="btn btn-success" href="{% url 'applications:webapp_add_pguser' webapp.pk %}">
    <span class="glyphicon glyphicon-plus"></span> {% trans "Add PostgreSQL user" %}</a>
</div>
<h2>{% trans "PostgreSQL users" %}</h2>
<br>
{% if pg_users %}
<table class="table table-striped table-hover">
<tr>
    <th>{% trans "User name" %}</th>
    <th>{% trans "Password" %}</th>
    <th>{% trans "DB Server" %}</th>
    <th></th>
</tr>
{% for pg_user in pg_users %}
<tr>
    <td>{{ pg_user.username }}</td>
    <td><input class="__anchor-password_input__{{ forloop.counter }}" type="password" value="{{ pg_user.password }}">
    <a class="__label-show_hide_text__{{ forloop.counter }}" href="javascript:show_password({{ forloop.counter }})">{% trans "Show" %}</a>
    </td>
    <td>{{ pg_user.pg_service }}</td>
    <td style="text-align:right;">
    {% if perms.services.delete_postgresqluser %}
    <a href="{% url 'applications:webapp_remove_pguser' webapp.pk pg_user.pk %}" class="btn btn-danger btn-sm {% if pg_user.can_be_deleted == False %} disabled{% endif %}">
    <span class="glyphicon glyphicon-trash" title="{% trans 'Delete' %}"></span></a>
    {% endif %}
    </td>
</tr>
{% endfor %}

</table>
{% else %}
<div class="alert alert-info">
<p>{% trans "There are no PostgreSQL users binded to this web application." %}</p>
</div>
{% endif %}
<hr>

<div class="btn-toolbar pull-right">
    <a class="btn btn-success" href="{% url 'applications:webapp_add_pgdb' webapp.pk %}">
    <span class="glyphicon glyphicon-plus"></span> {% trans "Add PostgreSQL database" %}</a>
</div>
<h2>{% trans "PostgreSQL databases" %}</h2>
<br>
{% if pg_databases %}
<table class="table table-striped">
<tr>
    <th>{% trans "Name" %}</th>
    <th>{% trans "User name" %}</th>
    <th>{% trans "DB server" %}</th>
    <th></th>
</tr>
{% for pg_db in pg_databases %}
<tr>
    <td>{{ pg_db.name }}</td>
    <td>{{ pg_db.username }}</td>
    <td>{{ pg_db.pg_service }}</td>
    <td>
    <div class="btn-toolbar pull-right">
    <div class="btn-group">
    <a href="{% url 'applications:webapp_pgconnection' webapp.pk pg_db.pk %}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-info-sign" title="{% trans 'Connection info' %}"></span></a>
    <a href="{% url 'applications:webapp_pgdumps' webapp.pk pg_db.pk %}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-hdd" title="{% trans 'Dumps/Load' %}"></span></a>
    </div>
    <div class="btn-group">
    <a href="{% url 'applications:webapp_remove_pgdb' webapp.pk pg_db.pk %}" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash" title="{% trans 'Delete' %}"></span></a>
    </div>
    </div>
    </td>
</tr>
{% endfor %}
</table>
{% else %}
<div class="alert alert-info">
<p>{% trans "There are no PostgreSQL databases binded to this web application." %}</p>
</div>
{% endif %}

<script type="text/javascript">
    function show_password(id) {
        var e = $(".__anchor-password_input__"+id);
        var type = e.attr("type");
        if(type === "password") {
            e.attr("type", "text");
            $(".__label-show_hide_text__"+id).html("{% trans 'Hide' %}")
        } else {
            e.attr("type", "password");
            $(".__label-show_hide_text__"+id).html("{% trans 'Show' %}")
        }
    }
</script>
{% endblock %}

host_panel/applications/templates/applications/domain_list.html
{% extends "applications/webapp_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load navigation_tags %}

{% block breadcrumbs %}
{{ block.super }}
<li class="active">{% trans "Domains" %}</li>
{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
    <a class="btn btn-success" href="{% url 'applications:webapp_add_domain' webapp.pk %}">
    <span class="glyphicon glyphicon-plus"></span>
    {% trans "Add domain" %}</a>
</div>
<h2>{% trans "Domains" %}</h3>
<br>
{% if domains %}
<table class="table table-striped">
<tr>
    <th>{% trans "Domain" %}</th>
    <th>{% trans "Protocol" %}</th>
    <th>{% trans "Router" %}</th>
    <th>{% trans "Default" %}</th>
    <th></th>
</tr>
{% for domain in domains %}
<tr>
    <td><a href="{{ domain.protocol }}://{{ domain.domain }}" target="_blank">{{ domain.domain }}</a></td>
    <td>{{ domain.get_protocol_display }}</td>
    <td>{{ domain.hipache }}</td>
    <td>
    {% if domain.is_default %}
    <span class="glyphicon glyphicon-ok"></span>
    {% else %}
    <a href="{% url 'applications:webapp_set_default_domain' webapp.pk domain.pk %}">{% trans "Set default" %}</a>
    {% endif %}
    </td>
    <td style="text-align:right;">
    <a href="{% url 'applications:webapp_remove_domain' webapp.pk domain.pk %}" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash" title="{% trans 'Delete' %}"></span></a></td>
</tr>
{% endfor %}
</table>
{% else %}
<div class="alert alert-info">
<p>{% trans "There are no domains yet." %}</p>
</div>
{% endif %}
{% endblock %}

host_panel/applications/templates/applications/settings.html
{% extends "applications/webapp_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% load navigation_tags %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li class="active">{% trans "Server settings" %}</li>
{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
    <div class="btn-group">
    <a href="{% url 'applications:webapp_restart_nginx' webapp.pk %}"
    class="btn btn-default">
    <span class="glyphicon glyphicon-refresh"></span>
    {% trans "Restart Nginx" %}</a>    
    </div>
    <div class="btn-group">
    <a href="{% url 'applications:webapp_settings_mode' webapp.pk %}?mode=easy"
    class="btn btn-default{% if not server_settings.manual_config %} active{% endif %}">
    {% trans "Easy config" %}</a>
    <a href="{% url 'applications:webapp_settings_mode' webapp.pk %}?mode=manual"
    class="btn btn-default{% if server_settings.manual_config %} active{% endif %}">
    {% trans "Manual config" %}</a>
    </div>
</div>
<h2>{% trans "Server settings" %}</h2>
<br>

{% if server_settings.manual_config %}
<form role="form" method="post">
{% csrf_token %}
{{ form|crispy }}
<div class="form-group">
<button class="btn btn-primary" type="submit">
{% trans "Save" %}
</button>
</div>
</form>
{% else %}

<ul class="nav nav-tabs">
  <li class="active"><a href="#settings" data-toggle="tab">{% trans "Edit" %}</a></li>
  <li><a href="#preview" data-toggle="tab">{% trans "View webapp.conf" %}</a></li>
</ul>
<div class="tab-content">
  <div class="tab-pane active" id="settings">
  <br>

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "Domains" %}</h3>
</div>
<div class="panel-body">
<table class="table">
<tr>
    <td><strong>{% trans "Main domain" %}</strong></td>
    <td>{{ main_domain }}</td>
</tr>
{% for d in extra_domains %}
<tr>
    <td>{% if forloop.first %}<strong>{% trans "Extra domains" %}</strong>{% endif %}</td>
    <td>{{ d }}</td>
</tr>
{% endfor %}
</table>
</div>
</div>

{% crispy form %}
<br>
  </div>
  <div class="tab-pane" id="preview">
  <br>
<pre>
{{ server_settings.get_config_file }}
</pre>
  </div>
</div>
{% endif %}
{% endblock %}