host_panel/accounts/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout
from .views import (
    CustomerDetailView,
    MyAccountUpdateView,
)


urlpatterns = patterns(
    '',
    url(
        r'^login/$', login,
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(
        r'^my-account/edit/$',
        MyAccountUpdateView.as_view(),
        name='edit_my_account'),
    url(
        r'^(?P<pk>\d+)/$', CustomerDetailView.as_view(),
        name='customer_details'),
)

host_panel/hosts/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (
    HostListView,
    HostDetailView,
    HostCreateView,
    HostSSHKeyListView,
    HostSSHKeyCreateView,
    HostSSHKeyDeleteView,
    FTPUserListView,
    FTPUserCreateView,
    FTPUserDeleteView,
    DatabaseServiceListView,
    DatabaseServiceCreateView,
    DatabaseServiceDetailView,
    DatabaseServiceDeleteView,
    DatabaseServiceSSHKeyCreateView,
    DatabaseServiceSSHKeyDeleteView,
    HipacheInfoView,
    HipacheSSHKeyCreateView,
    HipacheSSHKeyDeleteView,
    CronTaskListView,
    CronTaskCreateView,
    CronTaskUpdateView,
    CronTaskDeleteView,
)

urlpatterns = patterns(
    'hosts.views',
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/(?P<pk>\d+)/remove/$',
        HipacheSSHKeyDeleteView.as_view(), name='host_routing_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/add/$',
        HipacheSSHKeyCreateView.as_view(), name='host_routing_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/install/$',
        'install_hipache', name='host_install_routing'),
    url(
        r'^(?P<host_pk>\d+)/routing/update-hipache-db/$',
        'update_hipache_db', name='host_update_hipache_db'),
    url(
        r'^(?P<host_pk>\d+)/routing/$',
        HipacheInfoView.as_view(), name='host_routing'),

    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<db_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        DatabaseServiceSSHKeyDeleteView.as_view(),
        name='host_database_service_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/sshkeys/add/$',
        DatabaseServiceSSHKeyCreateView.as_view(),
        name='host_database_service_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/remove/$',
        DatabaseServiceDeleteView.as_view(),
        name='host_remove_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/$',
        DatabaseServiceDetailView.as_view(), name='host_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/add/$',
        DatabaseServiceCreateView.as_view(), name='host_add_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/$',
        DatabaseServiceListView.as_view(), name='host_database_services'),

    url(
        r'^(?P<host_pk>\d+)/ftpusers/add/$',
        FTPUserCreateView.as_view(), name='host_add_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/(?P<pk>\d+)/remove/$',
        FTPUserDeleteView.as_view(), name='host_remove_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/$',
        FTPUserListView.as_view(), name='host_ftpusers'),

    url(
        r'^(?P<host_pk>\d+)/run-command/(?P<button_id>\d+)/$',
        'host_run_command', name='run_command'),

    url(
        r'^(?P<host_pk>\d+)/sshkeys/add/$',
        HostSSHKeyCreateView.as_view(), name='host_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        HostSSHKeyDeleteView.as_view(), name='host_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/$',
        HostSSHKeyListView.as_view(), name='host_sshkeys'),

    url(
        r'^(?P<host_pk>\d+)/crontasks/add/$',
        CronTaskCreateView.as_view(), name='host_add_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/edit/$',
        CronTaskUpdateView.as_view(), name='host_edit_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/remove/$',
        CronTaskDeleteView.as_view(), name='host_remove_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/$',
        CronTaskListView.as_view(), name='host_crontasks'),

    url(
        r'^(?P<pk>\d+)/host-setup.sh$',
        'setup_script', name='host_setup_script'),
    url(
        r'^(?P<pk>\d+)/mark-manageable/$',
        'mark_manageable', name='host_mark_manageable'),

    url(
        r'^(?P<pk>\d+)/detail/$',
        HostDetailView.as_view(), name='host_detail'),
    url(r'^add/$', HostCreateView.as_view(), name='add_host'),
    url(r'^$', HostListView.as_view(), name='host_list'),
)

host_panel/accounts/models.py
# coding: utf-8
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


class CustomerManager(BaseUserManager):
    """
    Creates and saves a Customer with the given email, full_name and password.
    """
    def create_user(self, email, full_name='', password=None):
        """
        Creates and saves a Customer with the given email,
        full_name and password.
        """
        if not email:
            raise ValueError(_(u'Customers must have an email address'))

        customer = self.model(
            email=CustomerManager.normalize_email(email),
            full_name=full_name
        )
        customer.set_password(password)
        customer.save(using=self._db)
        return customer

    def create_superuser(self, email, full_name='', password=None):
        """
        Creates and saves a superuser with the given email,
        full_name and password.
        """
        customer = self.create_user(email, full_name, password)
        customer.is_admin = True
        customer.save(using=self._db)
        return customer


class Customer(AbstractBaseUser, PermissionsMixin):
    """
    A model which implements the authentication model.

    Email, password and full_name are required. Other fields are optional.

    Email field is used for logging in.
    """
    email = models.EmailField(
        _(u'Email'), max_length=255, unique=True)
    full_name = models.CharField(
        _(u'Full name'), max_length=100)

    language = models.CharField(
        _(u'Language'), default=settings.LANGUAGE_CODE,
        max_length=10, choices=settings.LANGUAGES)

    is_admin = models.BooleanField(_(u'Admin status'), default=False)
    is_active = models.BooleanField(_(u'Active'), default=True)

    date_joined = models.DateTimeField(_(u'Date joined'), default=timezone.now)

    objects = CustomerManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    class Meta:
        verbose_name = _(u'Customer')
        verbose_name_plural = _(u'Customers')

    def __unicode__(self):
        return self.full_name or self.email

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

host_panel/accounts/forms.py
# coding: utf-8
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from .models import Customer


class CustomerChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        label=_(u'Password'),
        help_text=_(
            u'Raw passwords are not stored, so there is no way to see '
            u'this user\'s password, but you can change the password '
            u'using <a href="password/">this form</a>.'))

    class Meta:
        model = Customer
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CustomerChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        return self.initial['password']


class CustomerCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges,
    from the given email, full_name and password.
    """
    error_messages = {
        'duplicate_email': _(u"A user with that email already exists."),
        'duplicate_nickname': _(u"A user with that nickname already exists."),
        'password_mismatch': _(u"The two password fields didn't match."),
    }
    password1 = forms.CharField(
        label=_(u"Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_(u"Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_(u"Enter the same password as above, for verification."))

    class Meta:
        model = Customer
        fields = ('email', 'full_name',)

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            Customer.objects.get(email=email)
        except Customer.DoesNotExist:
            return email
        raise forms.ValidationError(self.error_messages['duplicate_email'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        customer = super(CustomerCreationForm, self).save(commit=False)
        customer.set_password(self.cleaned_data["password1"])
        if commit:
            customer.save()
        return customer


class EditAccountForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = (
            'email', 'full_name', 'language')

    def __init__(self, *args, **kwargs):
        super(EditAccountForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
            Fieldset(
                _(u'General'),
                'email',
                'full_name',
                'language',
            ),
            ButtonHolder(
                Submit('submit', _(u'Save'), css_class='btn btn-primary')
            )
        )

host_panel/accounts/views.py
# coding: utf-8
from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from django.views.generic.detail import DetailView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from django.contrib.messages.views import SuccessMessageMixin
from .models import Customer
from .forms import EditAccountForm


class CustomerDetailView(DetailView):
    model = Customer
    context_object_name = 'customer'


class MyAccountUpdateView(SuccessMessageMixin, UpdateView):
    model = Customer
    template_name = 'accounts/edit_my_account.html'
    form_class = EditAccountForm
    success_message = _(u"Your account settings was changed.")

    def get_object(self):
        return Customer.objects.get(pk=self.request.user.pk)

    def get_success_url(self):
        return reverse(
            'customer_details', args=(self.request.user.pk,))

host_panel/accounts/templates/accounts/customer_detail.html
{% extends "one_column_page.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} - {% trans "Customer account" %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li class="active">{% trans "Customer account" %}</li>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-3">
<img src="{% static 'accounts/img/default-user-icon-profile.png' %}">
</div>
<div class="col-md-9">
{% if user == customer %}
<div class="btn-toolbar pull-right">
<a href="{% url 'edit_my_account' %}" class="btn btn-success">
<span class="glyphicon glyphicon-edit"></span>
{% trans "Edit account" %}</a>
</div>
{% endif %}
<h1>{{ customer.get_full_name }}</h1>
<br>
<dl>
    <dt>{% trans "Email" %}</dt>
    <dd>{{ customer.email }}</dd>
    <dt>{% trans "Language" %}</dt>
    <dd>{{ customer.get_language_display }}</dd>
</dl>
</div>
</div>
{% endblock %}

host_panel/accounts/templates/accounts/edit_my_account.html
{% extends "one_column_page.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Edit account" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'customer_details' user.pk %}">{% trans "Customer account" %}</a></li>
<li class="active">{% trans "Edit account" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Edit account" %}</h2>

{% crispy form %}
{% endblock %}

host_panel/accounts/templates/accounts/login.html
{% extends "blank.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block extra_head %}
<link href="{% static 'accounts/css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block container %}
<form class="form-signin" role="form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<h2 class="form-signin-heading"><img src="{% static 'img/grape.png' %}"> Grape</h2>
{% if form.errors %}
<p class="text-danger">{% trans "Your username and password didn't match. Please try again." %}</p>
{% endif %}

<input name="username" type="email" class="form-control" placeholder="{{ form.username.label }}" required autofocus>
<input name="password" type="password" class="form-control" placeholder="{{ form.password.label }}" required>

<input type="hidden" name="next" value="{{ next }}" />
<button class="btn btn-lg btn-primary btn-block" type="submit">
{% trans "Log in" %}
</button>
</form>
{% endblock %}

host_panel/accounts/templates/accounts/user_toolbar.html
{% load i18n %}
{% if user.is_authenticated %}
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
  {{ user.get_full_name }} <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'customer_details' user.pk %}">{% trans "My account" %}</a></li>
    <li><a href="{% url 'sshkeys:list' %}">{% trans "SSH keys" %}</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'logout' %}">{% trans "Log out" %}</a></li>
  </ul>
</li>
{% endif %}