host_panel/applications/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (
    WebApplicationListView,
    WebApplicationCreateView,
    WebApplicationDetailView,
    WebApplicationDeleteView,
    WebappSSHKeyListView,
    WebappSSHKeyCreateView,
    WebappSSHKeyDeleteView,
    DatabaseUserCreateView,
    DatabaseUserDeleteView,
    DatabaseCreateView,
    DatabaseDeleteView,
    LinkedFTPListView,
    LinkedFTPCreateView,
    LinkedFTPDeleteView,
    DomainListView,
    DomainCreateView,
    DomainDeleteView,
    BackupToFTPLinkCreateView,
    BackupToFTPLinkDeleteView,
)


urlpatterns = patterns(
    'applications.views',
    url(
        r'^(?P<app_pk>\d+)/linkedftps/add/$',
        LinkedFTPCreateView.as_view(), name='webapp_add_linkedftp'),
    url(
        r'^(?P<app_pk>\d+)/linkedftps/(?P<pk>\d+)/remove/$',
        LinkedFTPDeleteView.as_view(), name='webapp_remove_linkedftp'),
    url(
        r'^(?P<app_pk>\d+)/linkedftps/$',
        LinkedFTPListView.as_view(), name='webapp_linkedftps'),


    url(
        r'^(?P<app_pk>\d+)/sshkeys/$',
        WebappSSHKeyListView.as_view(), name='webapp_sshkeys'),
    url(
        r'^(?P<app_pk>\d+)/sshkeys/add/$',
        WebappSSHKeyCreateView.as_view(),
        name='webapp_add_sshkey'),
    url(
        r'^(?P<app_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        WebappSSHKeyDeleteView.as_view(),
        name='webapp_remove_sshkey'),

    url(
        r'^(?P<app_pk>\d+)/domains/$',
        DomainListView.as_view(), name='webapp_domains'),
    url(
        r'^(?P<app_pk>\d+)/domains/(?P<pk>\d+)/remove/$',
        DomainDeleteView.as_view(), name='webapp_remove_domain'),
    url(
        r'^(?P<app_pk>\d+)/domains/(?P<pk>\d+)/set-default/$',
        'set_default_domain', name='webapp_set_default_domain'),
    url(
        r'^(?P<app_pk>\d+)/domains/add/$',
        DomainCreateView.as_view(), name='webapp_add_domain'),

    url(r'^(?P<app_pk>\d+)/files/$', 'files', name='webapp_files'),

    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/add/$',
        DatabaseCreateView.as_view(), name='webapp_add_pgdb'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/(?P<pk>\d+)/remove/$',
        DatabaseDeleteView.as_view(), name='webapp_remove_pgdb'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/(?P<pk>\d+)/connection/$',
        'pg_connection', name='webapp_pgconnection'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgdbs/(?P<pk>\d+)/dumps/$',
        'pg_dumps', name='webapp_pgdumps'),

    url(
        r'^(?P<app_pk>\d+)/databases/pgusers/(?P<pk>\d+)/remove/$',
        DatabaseUserDeleteView.as_view(), name='webapp_remove_pguser'),
    url(
        r'^(?P<app_pk>\d+)/databases/pgusers/add/$',
        DatabaseUserCreateView.as_view(), name='webapp_add_pguser'),
    url(
        r'^(?P<app_pk>\d+)/databases/$',
        'databases', name='webapp_databases'),

    url(
        r'^(?P<pk>\d+)/remove/$',
        WebApplicationDeleteView.as_view(), name='remove_webapp'),
    url(
        r'^(?P<pk>\d+)/$',
        WebApplicationDetailView.as_view(), name='webapp'),
    url(
        r'^add/$',
        WebApplicationCreateView.as_view(), name='add_webapp'),
    url(
        r'^$',
        WebApplicationListView.as_view(), name='application_list'),

    url(
        r'^(?P<app_pk>\d+)/backups/$',
        'backups_view', name='webapp_backups'),
    url(
        r'^(?P<app_pk>\d+)/backups/ftp-links/add/$',
        BackupToFTPLinkCreateView.as_view(), name='webapp_add_backup_ftp'),
    url(
        r'^(?P<app_pk>\d+)/backups/ftp-links/(?P<pk>\d+)/remove/$',
        BackupToFTPLinkDeleteView.as_view(), name='webapp_remove_backup_ftp'),
    url(
        r'^(?P<app_pk>\d+)/backups/edit/$',
        'configure_backups', name='webapp_configure_backups'),

    url(
        r'^(?P<app_pk>\d+)/settings/change-mode/$',
        'change_settings_mode', name='webapp_settings_mode'),
    url(
        r'^(?P<app_pk>\d+)/settings/restart-nginx/$',
        'restart_nginx', name='webapp_restart_nginx'),
    url(
        r'^(?P<app_pk>\d+)/settings/$',
        'settings', name='webapp_settings'),
)

host_panel/host_panel/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns(
    '',
    url(r'^$', 'host_panel.views.home', name='home'),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^hosts/', include('hosts.urls', namespace='hosts')),
    url(r'^applications/', include('applications.urls', namespace='applications')),
    url(r'^sshkeys/', include('sshkeys.urls', namespace='sshkeys')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

host_panel/hosts/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (
    HostListView,
    HostDetailView,
    HostCreateView,
    HostSSHKeyListView,
    HostSSHKeyCreateView,
    HostSSHKeyDeleteView,
    FTPUserListView,
    FTPUserCreateView,
    FTPUserDeleteView,
    DatabaseServiceListView,
    DatabaseServiceCreateView,
    DatabaseServiceDetailView,
    DatabaseServiceDeleteView,
    DatabaseServiceSSHKeyCreateView,
    DatabaseServiceSSHKeyDeleteView,
    HipacheInfoView,
    HipacheSSHKeyCreateView,
    HipacheSSHKeyDeleteView,
    CronTaskListView,
    CronTaskCreateView,
    CronTaskUpdateView,
    CronTaskDeleteView,
)

urlpatterns = patterns(
    'hosts.views',
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/(?P<pk>\d+)/remove/$',
        HipacheSSHKeyDeleteView.as_view(), name='host_routing_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/add/$',
        HipacheSSHKeyCreateView.as_view(), name='host_routing_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/install/$',
        'install_hipache', name='host_install_routing'),
    url(
        r'^(?P<host_pk>\d+)/routing/update-hipache-db/$',
        'update_hipache_db', name='host_update_hipache_db'),
    url(
        r'^(?P<host_pk>\d+)/routing/$',
        HipacheInfoView.as_view(), name='host_routing'),

    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<db_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        DatabaseServiceSSHKeyDeleteView.as_view(),
        name='host_database_service_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/sshkeys/add/$',
        DatabaseServiceSSHKeyCreateView.as_view(),
        name='host_database_service_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/remove/$',
        DatabaseServiceDeleteView.as_view(),
        name='host_remove_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/$',
        DatabaseServiceDetailView.as_view(), name='host_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/add/$',
        DatabaseServiceCreateView.as_view(), name='host_add_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/$',
        DatabaseServiceListView.as_view(), name='host_database_services'),

    url(
        r'^(?P<host_pk>\d+)/ftpusers/add/$',
        FTPUserCreateView.as_view(), name='host_add_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/(?P<pk>\d+)/remove/$',
        FTPUserDeleteView.as_view(), name='host_remove_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/$',
        FTPUserListView.as_view(), name='host_ftpusers'),

    url(
        r'^(?P<host_pk>\d+)/run-command/(?P<button_id>\d+)/$',
        'host_run_command', name='run_command'),

    url(
        r'^(?P<host_pk>\d+)/sshkeys/add/$',
        HostSSHKeyCreateView.as_view(), name='host_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        HostSSHKeyDeleteView.as_view(), name='host_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/$',
        HostSSHKeyListView.as_view(), name='host_sshkeys'),

    url(
        r'^(?P<host_pk>\d+)/crontasks/add/$',
        CronTaskCreateView.as_view(), name='host_add_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/edit/$',
        CronTaskUpdateView.as_view(), name='host_edit_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/remove/$',
        CronTaskDeleteView.as_view(), name='host_remove_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/$',
        CronTaskListView.as_view(), name='host_crontasks'),

    url(
        r'^(?P<pk>\d+)/host-setup.sh$',
        'setup_script', name='host_setup_script'),
    url(
        r'^(?P<pk>\d+)/mark-manageable/$',
        'mark_manageable', name='host_mark_manageable'),

    url(
        r'^(?P<pk>\d+)/detail/$',
        HostDetailView.as_view(), name='host_detail'),
    url(r'^add/$', HostCreateView.as_view(), name='add_host'),
    url(r'^$', HostListView.as_view(), name='host_list'),
)

host_panel/hosts/forms.py
# coding: utf-8
from django import forms
from django.forms import widgets
from django.utils.translation import ugettext_lazy as _
from .models import Host, HostSSHKey, FTPUser, CronTask, ServerType
from codemirror import CodeMirrorTextarea


class ServerTypeForm(forms.ModelForm):
    class Meta:
        model = ServerType
        fields = '__all__'
        widgets = {
            'build_script': CodeMirrorTextarea(
                mode="shell", config={'fixedGutter': True}),
        }


class EditHostForm(forms.ModelForm):
    class Meta:
        model = Host
        fields = '__all__'
        widgets = {
            'sudo_password': forms.PasswordInput(),
        }


class AddSSHKeyForm(forms.ModelForm):
    class Meta:
        model = HostSSHKey
        fields = ['key']

    def __init__(self, customer, host, *args, **kwargs):
        from sshkeys.models import SSHKey
        super(AddSSHKeyForm, self).__init__(*args, **kwargs)
        self.host = host
        self.fields['key'].queryset = SSHKey.objects.filter(owner=customer)

    def clean_key(self):
        from .models import HostSSHKey
        already_exist = HostSSHKey.objects.filter(
            host=self.host, key=self.cleaned_data['key']).exists()

        if not already_exist:
            return self.cleaned_data['key']
        raise forms.ValidationError(_(u'This key already added to host.'))


class AddFTPUserForm(forms.ModelForm):
    class Meta:
        model = FTPUser
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, host, *args, **kwargs):
        super(AddFTPUserForm, self).__init__(*args, **kwargs)
        self.host = host

    def clean_username(self):
        if not self.cleaned_data['username'].startswith('ftp-'):
            raise forms.ValidationError(_(u'Name of ftp user must starts with "ftp-".'))
        already_exist = FTPUser.objects.filter(
            host=self.host,
            username__exact=self.cleaned_data['username']).exists()

        if not already_exist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_(u'User already exists.'))


class AddCronTaskForm(forms.ModelForm):
    class Meta:
        model = CronTask
        fields = ['active', 'cron_time', 'command']
        widgets = {
            'command': widgets.TextInput(),
        }

host_panel/hosts/templates/hosts/crontask_list.html
{% extends "hosts/host_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load navigation_tags %}

{% block breadcrumbs %}
{{ block.super }}
<li class="active">{% trans "Cron tasks" %}</li>
{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
    <a class="btn btn-success" href="{% url 'hosts:host_add_crontask' host.pk %}">
    <span class="glyphicon glyphicon-plus"></span> {% trans "Add task" %}</a>
</div>
<h2>{% trans "Cron tasks" %}</h2>
<br>

{% if cron_tasks %}
<table class="table table-striped table-hover">
<tr>
    <th>{% trans "Cron time" %}</th>
    <th>{% trans "Command" %}</th>
    <th>{% trans "Added by" %}
    <th></th>
</tr>
{% for t in cron_tasks %}
<tr>
    <td><code{% if not t.active %} class="text-muted"{% endif %}>{{ t.cron_time }}</code></td>
    <td><code{% if not t.active %} class="text-muted"{% endif %} title="{{ t.command }}">{{ t.command|truncatechars:50 }}</code></td>
    <td{% if not t.active %} class="text-muted"{% endif %}>{{ t.added_by.get_full_name }}</td>
    <td style="text-align:right;">
        {% if not t.is_backup_task %}
        <a href="{% url 'hosts:host_edit_crontask' host.pk t.pk %}" class="btn btn-info btn-sm" title="{% trans 'Edit' %}"><span class="glyphicon glyphicon-edit"></span></a>
        {% endif %}
        <a href="{% url 'hosts:host_remove_crontask' host.pk t.pk %}" class="btn btn-danger btn-sm" title="{% trans 'Delete' %}"><span class="glyphicon glyphicon-trash"></span></a>
    </td>
</tr>
{% endfor %}
</table>
{% else %}
<div class="alert alert-info">
    <p>{% trans "There are no Cron tasks yet." %}</p>
</div>
{% endif %}
{% endblock %}

host_panel/hosts/templates/hosts/host_detail.html
{% extends "hosts/host_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load navigation_tags %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
<li><a href="{% url 'hosts:host_list' %}">{% trans "Hosts" %}</a></li>
<li class="active">{{ host.name }}</li>
{% endblock %}

{% block content %}
<h2>{{ host.name }}</h2>

{% if host.is_manageable %}
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "Description" %}</h3>
</div>
<div class="panel-body">
<table class="table">
<tr>
<td>
<dl class="dl-horizontal">
    <dt>{% trans "IP address" %}</dt>
    <dd>{{ host.ip_address }}</dd>
    <dt>{% trans "Host domain" %}</dt>
    <dd>{{ host.get_host_domain }}</dd>
    <dt>{% trans "Server type" %}</dt>
    <dd>{{ host.server_type }}</dd>
</dl>
</td>
<td>
{% if host.description %}
{{ host.get_description_as_html|safe }}
{% else %}
{% trans "No description." %}
{% endif %}
</td>
</tr>
</table>
</div>
</div>

<div class="panel panel-danger">
<div class="panel-heading">
<h3 class="panel-title">{% trans "Access info for admins" %}</h3>
</div>
<div class="panel-body">
<table class="table">
<tr>
    <td>{% trans "User" %}</td>
    <td>{{ host.main_user }}</td>
</tr>
<tr>
    <td>{% trans "Password" %}</td>
    <td>
    <input class="__anchor-password_input__1" type="password" value="{{ host.sudo_password }}">
    <a class="__label-show_hide_text__1" href="javascript:show_password(1)">{% trans "Show" %}</a>
    </td>
</tr>
<tr>
    <td>{% trans "Command for login" %}</td>
    <td><code>{{ host.get_ssh_command }}</code></td>
</tr>
</table>
</div>
</div>

{% if host.get_buttons %}
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "Host management commands" %}</h3>
</div>
<div class="panel-body">
<div class="btn-toolbar" role="toolbar">
<div class="btn-group">
{% for button in host.get_buttons %}
{% if button.new_group %}</div><div class="btn-group">{% endif %}
<a href="{% url 'hosts:run_command' host.pk button.pk %}" class="btn {{ button.button_class }}" title="{{ button.tooltip }}">{{ button.button_label }}</a>
{% endfor %}
</div>
</div>
</div>
</div>
{% endif %}

<script type="text/javascript">
    function show_password(id) {
        var e = $(".__anchor-password_input__"+id);
        var type = e.attr("type");
        if(type === "password") {
            e.attr("type", "text");
            $(".__label-show_hide_text__"+id).html("{% trans 'Hide' %}")
        } else {
            e.attr("type", "password");
            $(".__label-show_hide_text__"+id).html("{% trans 'Show' %}")
        }
    }
</script>
{% else %}
<div class="alert alert-warning">
    <p>{% trans "The setup of the host is not complete yet. Follow the instructions below." %}</p>
</div>

{% blocktrans %}
<p>You have to make some preparations for making the new host manageable.</p>

<p>Firstly, open terminal with <code>Ctrl+Alt+T</code> and use the next command for login:</p>
{% endblocktrans %}
<pre>
{{ host.get_ssh_command }}
</pre>
<p>{% trans "Use the next password when asked:" %} <code>{{ host.sudo_password }}</code></p>

<p>{% trans "Prepare to add the authorized ssh key:" %}</p>

<pre>
mkdir ~/.ssh && chmod 700 ~/.ssh
touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
</pre>

<p>{% trans "Open the file for edit:" %}</p>

<pre>
nano ~/.ssh/authorized_keys
</pre>

<p>{% trans "Copy the next public key to your clipboard:" %}

<pre>
{{ manage_key }}
</pre>

{% blocktrans %}
<p>Now paste it to the file with <code>Ctrl+Shift+V</code> and press Enter:</p>
{% endblocktrans %}
<div class="thumbnail">
<img src="{% static 'hosts/img/authorized-keys.png' %}">
</div>
{% blocktrans %}
<p>Then use <code>Ctrl+O</code> for save and <code>Ctrl+X</code> for exit from the editor.</p>
{% endblocktrans %}

{% blocktrans %}
<p>Now you need to go to the user home directory and download the script
for auto setup the host:</p>
{% endblocktrans %}

<div class="row">
<div class="col-sm-8">
<pre>
wget {{ panel_domain }}{% url "hosts:host_setup_script" host.pk %}
</pre>
</div>
<div class="col-sm-4">
<!-- Button trigger modal -->
<button class="btn btn-default btn-block" data-toggle="modal" data-target="#myModal">
{% trans "View setup script" %}
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">host-setup.sh</h4>
      </div>
      <div class="modal-body">
<textarea class="form-control" rows="15" readonly>
{{ host.server_type.build_script }}
</textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>
</div>

<p>{% trans "Give permission and run the script:" %}</p>

<pre>
chmod +x host-setup.sh
sudo ./host-setup.sh
</pre>

<p>{% trans "Wait while setup script prepare your host. It may take a couple of minutes." %}</p>

<p>{% trans "Pull the docker images:" %}</p>

<pre>{% for d in docker_images %}sudo docker pull {{ d.repository }}
{% endfor %}</pre>

{% blocktrans %}
<p>Now you have the ready new host for your infrastructure.
Press the button below and continue the setup.</p>
{% endblocktrans %}

<hr>
<div class="btn-toolbar">
    <a class="btn btn-success" href="{% url 'hosts:host_mark_manageable' host.pk %}">{% trans "Continue" %}</a>
</div>
<br>
{% endif %}
{% endblock %}

host_panel/hosts/templates/hosts/postgresql_add_sshkey.html
{% extends "hosts/host_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Add SSH key" %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'hosts:host_database_services' host.pk %}">{% trans "Database servers" %}</a></li>
<li><a href="{% url 'hosts:host_database_service' host.pk db_service.pk %}">{{ db_service.name }}</a></li>
<li class="active">{% trans "Add key" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Add SSH key" %}</h2>

<form role="form" method="post">
{% csrf_token %}
{{ form|crispy }}
<div class="form-group">
<button class="btn btn-primary" type="submit">
{% trans "Add key" %}
</button>
<a class="btn btn-link" href="{% url 'hosts:host_database_service' host.pk db_service.pk %}">{% trans "Cancel" %}</a>
</div>
</form>
{% endblock %}

host_panel/hosts/templates/hosts/postgresqlservice_detail.html
{% extends "hosts/host_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {{ db_service.name }}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'hosts:host_database_services' host.pk %}">{% trans "Database servers" %}</a></li>
<li class="active">{{ db_service.name }}</li>
{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
    <a href="{% url 'hosts:host_remove_database_service' host.pk db_service.pk %}" class="btn btn-danger">
    <span class="glyphicon glyphicon-trash"></span> {% trans "Remove" %}</a>
</div>
<h2>{{ db_service.name }}</h2>
<br>

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "Description" %}</h3>
</div>
<div class="panel-body">
<table class="table table-hover">
<tr>
    <td><strong>{% trans "IP Address" %}</strong></td>
    <td>{{ db_service.host.ip_address }}</td>
</tr>
<tr>
    <td><strong>{% trans "Port" %}</strong></td>
    <td>{{ db_service.public_service_port }}</td>
</tr>
<tr>
    <td><strong>{% trans "Container" %}</strong></td>
    <td>{{ db_service.docker_container }}</td>
</tr>
<tr>
    <td><strong>{% trans "Type" %}</strong></td>
    <td>{{ db_service.docker_container.docker_image }}</td>
</tr>
</table>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "SSH keys" %}</h3>
</div>
<div class="panel-body">
<div class="btn-toolbar">
    <a class="btn btn-success" href="{% url 'hosts:host_database_service_add_sshkey' host.pk db_service.pk %}">
    <span class="glyphicon glyphicon-plus"></span> {% trans "Add SSH key" %}</a>
</div>
<br>
{% with keys=db_service.docker_container.sshkeys.all %}
{% if keys %}
<table class="table table-striped table-hover">
<tr>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Added" %}</th>
    <th>{% trans "Owner" %}</th>
    <th></th>
</tr>
{% for key in keys %}
<tr>
    <td>{{ key.key.name }}</td>
    <td>{{ key.added|date:"d-m-Y" }}</td>
    <td>{{ key.added_by.get_full_name }}</td>
    <td style="text-align:right;">
        <a href="{% url 'hosts:host_database_service_remove_sshkey' host.pk db_service.pk key.pk %}" class="btn btn-danger btn-sm" title="{% trans 'Delete' %}"><span class="glyphicon glyphicon-trash"></span></a>
    </td>
</tr>
{% endfor %}
</table>
<p>{% trans "You can use that command for login to container:" %}
<code>{{ db_service.docker_container.get_ssh_command }}</code></p>
{% else %}
<div class="alert alert-info">
    <p>{% trans "There are no SSH keys yet." %}</p>
</div>
{% endif %}
{% endwith %}
</div>
</div>

{% with db_users=db_service.pg_users.all %}
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "PostgreSQL users" %}</h3>
</div>
<div class="panel-body">
{% if db_users %}
<table class="table table-striped table-hover">
<tr>
    <th>{% trans "User name" %}</th>
    <th>{% trans "Application" %}</th>
    <th>{% trans "Owner" %}</th>
</tr>
{% for db_user in db_users %}
<tr>
    <td>{{ db_user.username }}</td>
    <td><a href="{% url 'applications:webapp_databases' db_user.webapp.pk %}">{{ db_user.webapp.short_description }}</a></td>
    <td>{{ db_user.owner.get_full_name }}</td>
</tr>
{% endfor %}
</table>
{% else %}
<div class="alert alert-info">
    <p>{% trans "There are no PostgreSQL users yet." %}</p>
</div>
{% endif %}
</div>
</div>
{% endwith %}

{% with db_dbs=db_service.pg_databases.all %}
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "PostgreSQL databases" %}</h3>
</div>
<div class="panel-body">
{% if db_dbs %}
<table class="table table-striped table-hover">
<tr>
    <th>{% trans "DB name" %}</th>
    <th>{% trans "Application" %}</th>
    <th>{% trans "Owner" %}</th>
</tr>
{% for db in db_dbs %}
<tr>
    <td>{{ db.username }}</td>
    <td><a href="{% url 'applications:webapp_databases' db.webapp.pk %}">{{ db.webapp.short_description }}</a></td>
    <td>{{ db.owner.get_full_name }}</td>
</tr>
{% endfor %}
</table>
{% else %}
<div class="alert alert-info">
    <p>{% trans "There are no PostgreSQL users yet." %}</p>
</div>
{% endif %}
</div>
</div>
{% endwith %}
{% endblock %}