host_panel/host_panel/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns(
    '',
    url(r'^$', 'host_panel.views.home', name='home'),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^hosts/', include('hosts.urls', namespace='hosts')),
    url(r'^applications/', include('applications.urls', namespace='applications')),
    url(r'^sshkeys/', include('sshkeys.urls', namespace='sshkeys')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

host_panel/hosts/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (
    HostListView,
    HostDetailView,
    HostCreateView,
    HostSSHKeyListView,
    HostSSHKeyCreateView,
    HostSSHKeyDeleteView,
    FTPUserListView,
    FTPUserCreateView,
    FTPUserDeleteView,
    DatabaseServiceListView,
    DatabaseServiceCreateView,
    DatabaseServiceDetailView,
    DatabaseServiceDeleteView,
    DatabaseServiceSSHKeyCreateView,
    DatabaseServiceSSHKeyDeleteView,
    HipacheInfoView,
    HipacheSSHKeyCreateView,
    HipacheSSHKeyDeleteView,
    CronTaskListView,
    CronTaskCreateView,
    CronTaskUpdateView,
    CronTaskDeleteView,
)

urlpatterns = patterns(
    'hosts.views',
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/(?P<pk>\d+)/remove/$',
        HipacheSSHKeyDeleteView.as_view(), name='host_routing_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/sshkeys/add/$',
        HipacheSSHKeyCreateView.as_view(), name='host_routing_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/routing/install/$',
        'install_hipache', name='host_install_routing'),
    url(
        r'^(?P<host_pk>\d+)/routing/update-hipache-db/$',
        'update_hipache_db', name='host_update_hipache_db'),
    url(
        r'^(?P<host_pk>\d+)/routing/$',
        HipacheInfoView.as_view(), name='host_routing'),

    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<db_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        DatabaseServiceSSHKeyDeleteView.as_view(),
        name='host_database_service_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/sshkeys/add/$',
        DatabaseServiceSSHKeyCreateView.as_view(),
        name='host_database_service_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/remove/$',
        DatabaseServiceDeleteView.as_view(),
        name='host_remove_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/(?P<pk>\d+)/$',
        DatabaseServiceDetailView.as_view(), name='host_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/add/$',
        DatabaseServiceCreateView.as_view(), name='host_add_database_service'),
    url(
        r'^(?P<host_pk>\d+)/database-services/$',
        DatabaseServiceListView.as_view(), name='host_database_services'),

    url(
        r'^(?P<host_pk>\d+)/ftpusers/add/$',
        FTPUserCreateView.as_view(), name='host_add_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/(?P<pk>\d+)/remove/$',
        FTPUserDeleteView.as_view(), name='host_remove_ftpuser'),
    url(
        r'^(?P<host_pk>\d+)/ftpusers/$',
        FTPUserListView.as_view(), name='host_ftpusers'),

    url(
        r'^(?P<host_pk>\d+)/run-command/(?P<button_id>\d+)/$',
        'host_run_command', name='run_command'),

    url(
        r'^(?P<host_pk>\d+)/sshkeys/add/$',
        HostSSHKeyCreateView.as_view(), name='host_add_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/(?P<pk>\d+)/remove/$',
        HostSSHKeyDeleteView.as_view(), name='host_remove_sshkey'),
    url(
        r'^(?P<host_pk>\d+)/sshkeys/$',
        HostSSHKeyListView.as_view(), name='host_sshkeys'),

    url(
        r'^(?P<host_pk>\d+)/crontasks/add/$',
        CronTaskCreateView.as_view(), name='host_add_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/edit/$',
        CronTaskUpdateView.as_view(), name='host_edit_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/(?P<pk>\d+)/remove/$',
        CronTaskDeleteView.as_view(), name='host_remove_crontask'),
    url(
        r'^(?P<host_pk>\d+)/crontasks/$',
        CronTaskListView.as_view(), name='host_crontasks'),

    url(
        r'^(?P<pk>\d+)/host-setup.sh$',
        'setup_script', name='host_setup_script'),
    url(
        r'^(?P<pk>\d+)/mark-manageable/$',
        'mark_manageable', name='host_mark_manageable'),

    url(
        r'^(?P<pk>\d+)/detail/$',
        HostDetailView.as_view(), name='host_detail'),
    url(r'^add/$', HostCreateView.as_view(), name='add_host'),
    url(r'^$', HostListView.as_view(), name='host_list'),
)

host_panel/sshkeys/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (
    SSHKeyListView,
    SSHKeyCreateView,
    SSHKeyEditView,
    SSHKeyDeleteView,
)


urlpatterns = patterns(
    'sshkeys.views',
    url(r'^add/$', SSHKeyCreateView.as_view(), name='add_key'),
    url(
        r'^(?P<pk>\d+)/delete/$',
        SSHKeyDeleteView.as_view(), name='delete_key'),
    url(
        r'^(?P<pk>\d+)/edit/$',
        SSHKeyEditView.as_view(), name='edit_key'),
    url(r'^$', SSHKeyListView.as_view(), name='list'),
)

host_panel/sshkeys/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class SSHKey(models.Model):
    name = models.CharField(_(u'Name'), max_length=100)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_(u'Owner'))
    key = models.TextField(_(u'Key'))
    added = models.DateTimeField(_(u'Added'), auto_now_add=True)

    class Meta:
        verbose_name = _(u'SSH Key')
        verbose_name_plural = _(u'SSH Keys')
        unique_together = ('name', 'owner', 'key')

    def __unicode__(self):
        return self.name

host_panel/sshkeys/forms.py
# coding: utf-8
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import SSHKey


class SSHKeyForm(forms.ModelForm):

    class Meta:
        model = SSHKey
        fields = ['name', 'key']

    def __init__(self, owner, *args, **kwargs):
        super(SSHKeyForm, self).__init__(*args, **kwargs)
        self.owner = owner
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['key'].widget.attrs['readonly'] = True

    def clean_name(self):
        sshkeys = SSHKey.objects.filter(
            owner=self.owner, name=self.cleaned_data['name'])
        if sshkeys:
            raise forms.ValidationError(
                _(u'You already have SSH key with this name.'))
        else:
            return self.cleaned_data['name']

    def clean_key(self):
        sshkeys = SSHKey.objects.filter(
            owner=self.owner, key=self.cleaned_data['key'])
        if sshkeys and not self.fields['key'].widget.attrs['readonly']:
            raise forms.ValidationError(
                _(u'You already have this SSH key.'))
        else:
            return self.cleaned_data['key']

host_panel/sshkeys/views.py
# coding: utf-8
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic import CreateView, UpdateView, DeleteView
from host_panel.mixins import CheckOwnerMixin
from .models import SSHKey
from .forms import SSHKeyForm


class SSHKeyListView(ListView):
    model = SSHKey
    context_object_name = 'keys'

    def get_queryset(self):
        user = self.request.user
        return SSHKey.objects.filter(owner=user)


class SSHKeyCreateView(CreateView):
    model = SSHKey
    form_class = SSHKeyForm
    success_url = reverse_lazy('sshkeys:list')

    def get_form_kwargs(self):
        kwargs = super(SSHKeyCreateView, self).get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs

    def form_valid(self, form):
        key = form.save(commit=False)
        key.owner = self.request.user
        key.save()
        return super(SSHKeyCreateView, self).form_valid(form)


class SSHKeyEditView(CheckOwnerMixin, UpdateView):
    model = SSHKey
    form_class = SSHKeyForm
    success_url = reverse_lazy('sshkeys:list')

    def get_form_kwargs(self):
        kwargs = super(SSHKeyEditView, self).get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs


class SSHKeyDeleteView(CheckOwnerMixin, DeleteView):
    model = SSHKey
    success_url = reverse_lazy('sshkeys:list')

host_panel/sshkeys/templates/sshkeys/sshkey_confirm_delete.html
{% extends "one_column_page.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Delete SSH Key" %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'sshkeys:list' %}">{% trans "SSH Keys" %}</a></li>
<li class="active">{% trans "Delete SSH key" %}</li>
{% endblock %}

{% block content %}
<form role="form" method="post">
{% csrf_token %}
{{ form|crispy }}
<div class="alert alert-danger">
<p>{% blocktrans %}Are you sure you want to delete SSH key "{{ object }}"?{% endblocktrans %}</p>
</div>
<div class="form-group">
    <input type="submit" class="btn btn-danger" value="{% trans 'Delete' %}" />
<a class="btn btn-link" href="{% url 'sshkeys:list' %}">{% trans "Cancel" %}</a>
</div>
</form>
{% endblock %}

host_panel/sshkeys/templates/sshkeys/sshkey_form.html
{% extends "one_column_page.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Add SSH Key" %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'sshkeys:list' %}">{% trans "SSH Keys" %}</a></li>
<li class="active">{% if object %}{% trans "Edit SSH key" %} "{{ object }}"{% else %}{% trans "Add key" %}{% endif %}</li>
{% endblock %}

{% block content %}
<h2>{% if object %}{% trans "Edit SSH key" %} "{{ object }}"{% else %}{% trans "Add SSH Key" %}{% endif %}</h2>

<form role="form" method="post">
{% csrf_token %}
{{ form|crispy }}
<div class="form-group">
<button class="btn btn-primary" type="submit">
{% if object %}
{% trans "Save key" %}
{% else %}
{% trans "Add key" %}
{% endif %}
</button>
<a class="btn btn-link" href="{% url 'sshkeys:list' %}">{% trans "Cancel" %}</a>
</div>
</form>
{% endblock %}

host_panel/sshkeys/templates/sshkeys/sshkey_list.html
{% extends "one_column_page.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} - {% trans "SSH Keys" %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li class="active">{% trans "SSH Keys" %}</li>
{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
    <a class="btn btn-success" href="{% url 'sshkeys:add_key' %}">
    <span class="glyphicon glyphicon-plus"></span> {% trans "Add key" %}</a>
</div>
<h2>{% trans "SSH Keys" %}</h2>
<br>

{% if keys %}
<table class="table table-striped table-hover">
<tr>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Added" %}</th>
    <th></th>
</tr>
{% for key in keys %}
<tr>
    <td>{{ key.name }}</td>
    <td>{{ key.added|date:"d-m-Y" }}</td>
    <td style="text-align:right;">
        <a href="{% url 'sshkeys:edit_key' key.pk %}" class="btn btn-info btn-sm" title="{% trans 'Edit' %}"><span class="glyphicon glyphicon-edit"></span></a>
        <a href="{% url 'sshkeys:delete_key' key.pk %}" class="btn btn-danger btn-sm" title="{% trans 'Delete' %}"><span class="glyphicon glyphicon-trash"></span></a>
    </td>
</tr>
{% endfor %}
</table>
{% else %}
<div class="alert alert-info">
    <p>{% trans "There are no SSH keys yet." %}</p>
</div>
{% endif %}


<div class="panel panel-info">
<div class="panel-heading">
<h3 class="panel-title">{% trans "How to generate SSH key" %}</h3>
</div>
<div class="panel-body">
{% blocktrans %}
<p>Host and container administration can work only with ssh keys.
You can generate own key on your machine with command:</p>
<pre>ssh-keygen -t dsa</pre>
{% endblocktrans %}
</div>
</div>
{% endblock %}